[package]
name = "elliemakesmanygames/efsm"
description = "finite or dynamic state machine made with a procedural-oriented pattern"
license = "MIT"
authors = ["elliemakesmanygames"]
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["ESFM.code-workspace, sourcemap.json, default.project.json, .gitignore"]

[dependencies]
